Servers:
  Server1:
    ip: 'ip1.test.net'
    motd: '&cServer Ip1'
    #file: '' # Custom Server Icon file name
  Server2:
    ip: 'ip2.test.net'
    motd: 'icon2.png'
Default:
  motd: '&cMotd'

debug: false